import type { BlogPost, Equipment } from "@/lib/types";

export const company = {
  name: "Edil Mashinalary",
  phoneDisplay: "+996 551 000 303",
  phone: "+996551000303",
  whatsapp: "https://wa.me/996551000303",
  instagram: "https://www.instagram.com/edilmashinalary",
  email: "edilmashinalary@gmail.com",
  address: "Кыргызстан, Чуйская область, Новопокровка, ул. Ленина, 633",
  map: "https://www.google.com/maps/search/?api=1&query=633+%D1%83%D0%BB.+%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0+%D0%9D%D0%BE%D0%B2%D0%BE%D0%BF%D0%BE%D0%BA%D1%80%D0%BE%D0%B2%D0%BA%D0%B0+%D0%9A%D1%8B%D1%80%D0%B3%D1%8B%D0%B7%D1%81%D1%82%D0%B0%D0%BD",
} as const;

const loaderEquipment = [
  "Джойстиковое управление",
  "Кондиционер",
  "Быстросъём ковша",
  "Дополнительная гидролиния",
  "Камера заднего вида",
];

export const equipment: Equipment[] = [
  {
    id: "eq-lg393",
    slug: "lg393",
    name: "LG393",
    brand: "LGZT",
    category: "loaders",
    status: "in-stock",
    published: true,
    featured: true,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: "1,5 м³",
    loadCapacity: "2 т",
    power: 115,
    engine: "YCD4J22T-115",
    cylinders: 4,
    turbo: true,
    warrantyHours: 3000,
    promo: "На складе",
    shortDescription:
      "Универсальный фронтальный погрузчик для стройки, базы и коммунальных задач.",
    description:
      "LG393 закрывает ежедневные погрузочные задачи, уверенно работает с сыпучими материалами и навесным оборудованием. Джойстиковое управление, быстросъём и дополнительная гидролиния помогают быстрее менять рабочий сценарий прямо на площадке.",
    images: ["/images/products/lg393.webp", "/images/products/loader-site.jpg"],
    specs: [
      { label: "Тип", value: "Фронтальный погрузчик" },
      { label: "Грузоподъёмность", value: "2 000 кг" },
      { label: "Объём ковша", value: "1,5 м³" },
      { label: "Двигатель", value: "YCD4J22T-115" },
      { label: "Мощность", value: "115 л.с." },
      { label: "Управление", value: "Джойстик" },
    ],
    equipment: loaderEquipment,
    keywords: ["погрузчик", "lgzt", "1.5 м3", "стройка", "склад"],
  },
  {
    id: "eq-lg936",
    slug: "lg936",
    name: "LG936",
    brand: "LGZT",
    category: "loaders",
    status: "on-order",
    published: true,
    featured: true,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: "1,8 м³",
    loadCapacity: "3 т",
    power: 125,
    engine: "Weichai",
    cylinders: null,
    turbo: true,
    warrantyHours: 3000,
    promo: null,
    shortDescription:
      "Погрузчик трёхтонного класса для стройки, карьера и коммунальных работ.",
    description:
      "LG936 рассчитан на плотный рабочий график и задачи, где нужен запас грузоподъёмности. Комплектацию, двигатель и сроки поставки менеджер сверит перед оформлением заказа.",
    images: ["/images/products/loader-site.jpg", "/images/hero-warehouse.png"],
    specs: [
      { label: "Тип", value: "Фронтальный погрузчик" },
      { label: "Грузоподъёмность", value: "3 т" },
      { label: "Объём ковша", value: "1,8 м³" },
      { label: "Мощность", value: "125 л.с." },
      { label: "Двигатель", value: "Weichai" },
    ],
    equipment: loaderEquipment.slice(0, 4),
    keywords: ["lg936", "погрузчик", "3 тонны", "карьер", "weichai"],
  },
  {
    id: "eq-lg939",
    slug: "lg939",
    name: "LG939",
    brand: "LGZT",
    category: "loaders",
    status: "in-stock",
    published: true,
    featured: true,
    price: 2_068_000,
    oldPrice: 2_150_000,
    downPayment: 1_166_000,
    monthlyPayment: 75_167,
    installmentMonths: 12,
    bucket: "1,5 м³",
    loadCapacity: "2 т",
    power: 115,
    engine: "Weichai",
    cylinders: 4,
    turbo: true,
    warrantyHours: 3000,
    promo: "Выгода 82 000 сом",
    shortDescription:
      "Манёвренный погрузчик с ковшом 1,5 м³ и рассрочкой без банка.",
    description:
      "LG939 подходит для строительной площадки, склада, хозяйства и коммунальных работ. Модель доступна с прямой рассрочкой: паспорт, первый взнос и понятный график до 12 месяцев.",
    images: ["/images/hero-fleet.png", "/images/products/heavy-site.jpg"],
    specs: [
      { label: "Тип", value: "Фронтальный погрузчик" },
      { label: "Объём ковша", value: "1,5 м³" },
      { label: "Грузоподъёмность", value: "2 т" },
      { label: "Двигатель", value: "Weichai" },
      { label: "Цилиндры", value: "4" },
      { label: "Турбина", value: "Есть" },
    ],
    equipment: loaderEquipment,
    keywords: ["lg939", "погрузчик", "1,5 м³", "рассрочка", "weichai"],
  },
  {
    id: "eq-lg933",
    slug: "lg933",
    name: "LG933",
    brand: "LGZT",
    category: "loaders",
    status: "in-stock",
    published: true,
    featured: true,
    price: 1_804_000,
    oldPrice: null,
    downPayment: 1_034_000,
    monthlyPayment: 64_167,
    installmentMonths: 12,
    bucket: "1 м³",
    loadCapacity: "1,5 т",
    power: 103,
    engine: "Weichai",
    cylinders: 4,
    turbo: true,
    warrantyHours: 3000,
    promo: "Рассрочка до 12 месяцев",
    shortDescription:
      "Компактный рабочий погрузчик для базы, фермы и небольшой стройки.",
    description:
      "LG933 сочетает компактные размеры с оснащением полноценного фронтального погрузчика. Подходит там, где важны манёвренность, быстрый навес и понятные расходы на обслуживание.",
    images: ["/images/products/heavy-site.jpg", "/images/hero-warehouse.png"],
    specs: [
      { label: "Объём ковша", value: "1 м³" },
      { label: "Грузоподъёмность", value: "1,5 т" },
      { label: "Мощность", value: "103 л.с." },
      { label: "Двигатель", value: "Weichai" },
      { label: "Цилиндры", value: "4" },
      { label: "Турбина", value: "Есть" },
    ],
    equipment: loaderEquipment,
    keywords: ["lg933", "компактный погрузчик", "1 м3", "ферма"],
  },
  {
    id: "eq-lg920",
    slug: "lg920",
    name: "LG920",
    brand: "LGZT",
    category: "loaders",
    status: "in-stock",
    published: true,
    featured: true,
    price: 1_364_000,
    oldPrice: null,
    downPayment: 814_000,
    monthlyPayment: 45_833,
    installmentMonths: 12,
    bucket: "0,5 м³",
    loadCapacity: "0,8 т",
    power: 50,
    engine: "Weichai",
    cylinders: 4,
    turbo: false,
    warrantyHours: 3000,
    promo: "Первый взнос 814 000 сом",
    shortDescription:
      "Компактная модель для склада, небольшого хозяйства и узких площадок.",
    description:
      "LG920 удобен для работы на ограниченной территории. Простая конструкция двигателя, компактный ковш и небольшой радиус разворота делают его понятным выбором для склада и хозяйства.",
    images: ["/images/hero-warehouse.png", "/images/products/excavator-field.jpg"],
    specs: [
      { label: "Объём ковша", value: "0,5 м³" },
      { label: "Грузоподъёмность", value: "0,8 т" },
      { label: "Мощность", value: "50 л.с." },
      { label: "Двигатель", value: "Weichai" },
      { label: "Цилиндры", value: "4" },
      { label: "Форсунки", value: "Простые" },
    ],
    equipment: loaderEquipment.slice(0, 3),
    keywords: ["lg920", "малый погрузчик", "склад", "0,5 м3"],
  },
  {
    id: "eq-t933l",
    slug: "t933l",
    name: "T933L",
    brand: "LGZT",
    category: "loaders",
    status: "on-order",
    published: true,
    featured: false,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: "1,1 м³",
    loadCapacity: "2 т",
    power: 74,
    engine: null,
    cylinders: null,
    turbo: null,
    warrantyHours: 3000,
    promo: null,
    shortDescription:
      "Компактный фронтальный погрузчик с комфортной кабиной и быстрым навесом.",
    description:
      "T933L рассчитан на базу, ферму и склад. Точную комплектацию и срок поставки подтвердим перед заключением договора.",
    images: ["/images/hero-service.png", "/images/products/loader-site.jpg"],
    specs: [
      { label: "Объём ковша", value: "1,1 м³" },
      { label: "Грузоподъёмность", value: "2 т" },
      { label: "Мощность", value: "74 л.с." },
    ],
    equipment: loaderEquipment,
    keywords: ["t933l", "погрузчик", "ферма", "склад"],
  },
  {
    id: "eq-zl930",
    slug: "zl930",
    name: "ZL930",
    brand: "ZL",
    category: "loaders",
    status: "in-stock",
    published: true,
    featured: true,
    price: 3_080_000,
    oldPrice: null,
    downPayment: 1_672_000,
    monthlyPayment: 117_333,
    installmentMonths: 12,
    bucket: "1,8 м³",
    loadCapacity: "3 т",
    power: 125,
    engine: "Weichai",
    cylinders: 6,
    turbo: true,
    warrantyHours: 3000,
    promo: "В наличии",
    shortDescription:
      "Трёхтонный погрузчик с двигателем Weichai для высокой загрузки.",
    description:
      "ZL930 рассчитан на интенсивные погрузочные работы. Шестицилиндровый двигатель, ковш 1,8 м³ и грузоподъёмность 3 т подходят для стройки, базы и карьера.",
    images: ["/images/products/dump-truck.jpg", "/images/hero-fleet.png"],
    specs: [
      { label: "Объём ковша", value: "1,8 м³" },
      { label: "Грузоподъёмность", value: "3 т" },
      { label: "Мощность", value: "125 л.с." },
      { label: "Двигатель", value: "Weichai" },
      { label: "Цилиндры", value: "6" },
      { label: "Турбина", value: "Есть" },
    ],
    equipment: loaderEquipment,
    keywords: ["zl930", "3 тонны", "1,8 м3", "карьер", "weichai"],
  },
  {
    id: "eq-lg946",
    slug: "lg946",
    name: "LG946",
    brand: "LGZT",
    category: "loaders",
    status: "on-order",
    published: true,
    featured: false,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: null,
    loadCapacity: null,
    power: null,
    engine: null,
    cylinders: null,
    turbo: null,
    warrantyHours: 3000,
    promo: null,
    shortDescription:
      "Фронтальный погрузчик тяжёлого класса. Комплектация подбирается под задачу.",
    description:
      "LG946 поставляется под заказ. Мы не публикуем неподтверждённые параметры: менеджер уточнит двигатель, ковш, грузоподъёмность и комплектацию для конкретной поставки.",
    images: ["/images/products/tracked-loader.jpg", "/images/products/heavy-site.jpg"],
    specs: [{ label: "Поставка", value: "Под заказ" }],
    equipment: ["Подбор комплектации", "Расчёт поставки", "Гарантийная поддержка"],
    keywords: ["lg946", "тяжелый погрузчик", "под заказ"],
  },
  {
    id: "eq-howo-tx-6x4",
    slug: "howo-tx-6x4",
    name: "HOWO TX 6×4",
    brand: "HOWO",
    category: "dump-trucks",
    status: "on-order",
    published: true,
    featured: true,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: null,
    loadCapacity: null,
    power: null,
    engine: null,
    cylinders: null,
    turbo: null,
    warrantyHours: 3000,
    promo: "Поставка под задачу",
    shortDescription:
      "Самосвал с колёсной формулой 6×4 для стройки и перевозки материалов.",
    description:
      "HOWO TX 6×4 поставляется под заказ. Грузоподъёмность, двигатель, объём кузова и комплектацию согласуем до подписания договора.",
    images: ["/images/products/dump-truck.jpg", "/images/products/mixer-truck.jpg"],
    specs: [
      { label: "Тип", value: "Самосвал" },
      { label: "Колёсная формула", value: "6×4" },
      { label: "Поставка", value: "Под заказ" },
    ],
    equipment: ["Подбор конфигурации", "Расчёт поставки", "Консультация по эксплуатации"],
    keywords: ["howo", "самосвал", "6x4", "перевозка"],
  },
  {
    id: "eq-tj150",
    slug: "tj150",
    name: "TJ150",
    brand: "TJ",
    category: "excavators",
    status: "on-order",
    published: true,
    featured: false,
    price: null,
    oldPrice: null,
    downPayment: null,
    monthlyPayment: null,
    installmentMonths: 12,
    bucket: null,
    loadCapacity: null,
    power: null,
    engine: null,
    cylinders: null,
    turbo: null,
    warrantyHours: 3000,
    promo: null,
    shortDescription:
      "Колёсный экскаватор для земляных и коммунальных работ.",
    description:
      "TJ150 доступен под заказ. Рабочую массу, ковш, двигатель и навесное оборудование подберём под условия вашей площадки.",
    images: ["/images/products/excavator-city.jpg", "/images/products/excavator-field.jpg"],
    specs: [
      { label: "Тип", value: "Колёсный экскаватор" },
      { label: "Поставка", value: "Под заказ" },
    ],
    equipment: ["Подбор ковша", "Расчёт доставки", "Консультация по эксплуатации"],
    keywords: ["tj150", "экскаватор", "земляные работы", "колесный"],
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "loader-winter-checklist",
    title: "Как подготовить погрузчик к зиме",
    excerpt: "Короткий чек-лист по жидкостям, аккумулятору, шинам и запуску в мороз.",
    category: "Эксплуатация",
    readTime: "6 мин",
    image: "/images/hero-service.png",
    publishedAt: "20 августа 2026",
  },
  {
    slug: "weichai-service",
    title: "Как обслуживать двигатель Weichai",
    excerpt: "Что проверять ежедневно и какие интервалы обслуживания нельзя пропускать.",
    category: "Сервис",
    readTime: "7 мин",
    image: "/images/products/lg393.webp",
    publishedAt: "12 августа 2026",
  },
  {
    slug: "installment-without-bank",
    title: "Как рассчитать рассрочку без банка",
    excerpt: "Разбираем первый взнос, остаток и ежемесячный платёж на понятном примере.",
    category: "Покупка",
    readTime: "4 мин",
    image: "/images/hero-warehouse.png",
    publishedAt: "4 августа 2026",
  },
  {
    slug: "choose-bucket-volume",
    title: "Как выбрать объём ковша",
    excerpt: "Почему материал, плотность и высота выгрузки важнее одной цифры в каталоге.",
    category: "Выбор техники",
    readTime: "5 мин",
    image: "/images/products/heavy-site.jpg",
    publishedAt: "28 июля 2026",
  },
  {
    slug: "loader-or-tractor",
    title: "Погрузчик или трактор: что выбрать",
    excerpt: "Сравниваем рабочие сценарии, навесное оборудование и стоимость владения.",
    category: "Сравнение",
    readTime: "8 мин",
    image: "/images/products/loader-site.jpg",
    publishedAt: "19 июля 2026",
  },
  {
    slug: "reduce-downtime",
    title: "Как снизить простой техники",
    excerpt: "Плановый осмотр, запас расходников и простая дисциплина оператора.",
    category: "Бизнес",
    readTime: "5 мин",
    image: "/images/products/dump-truck.jpg",
    publishedAt: "8 июля 2026",
  },
];

export { categoryLabels } from "./categories";

export function formatPrice(value: number | null) {
  return value === null
    ? "Уточнить цену"
    : `${new Intl.NumberFormat("ru-RU").format(value)} сом`;
}

export function getEquipmentBySlug(slug: string) {
  return equipment.find((item) => item.slug === slug && item.published);
}
