import { Bot, MessageCircleQuestion, Save, Trash2 } from "lucide-react";
import { createChatAnswerAction, deleteChatAnswerAction, updateChatAnswerAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/auth";

export default async function AdminChatbotPage() {
  const { supabase } = await requireAdmin();
  const { data: answers } = await supabase.from("chat_answers").select("*").order("sort_order");
  return <><header className="admin-page-head"><div><span className="eyebrow">ПОМОЩНИК НА САЙТЕ</span><h1>Ответы чат-бота</h1><p>Редактируйте, отключайте и удаляйте готовые сценарии.</p></div></header><div className="admin-dashboard-grid"><section className="admin-panel"><div className="admin-panel-head"><div><span className="eyebrow">СЦЕНАРИИ</span><h2>{answers?.length ?? 0} ответов</h2></div><Bot aria-hidden="true" /></div><div className="admin-answer-list editable">{answers?.map((item) => <article key={item.id}><span><MessageCircleQuestion aria-hidden="true" /></span><form action={updateChatAnswerAction}><input type="hidden" name="id" value={item.id} /><input name="question" defaultValue={item.question} aria-label="Вопрос" /><textarea name="answer" defaultValue={item.answer} rows={3} aria-label="Ответ" /><label><input type="checkbox" name="active" defaultChecked={item.active} />Показывать на сайте</label><button className="admin-table-action"><Save aria-hidden="true" />Сохранить</button></form><form action={deleteChatAnswerAction}><input type="hidden" name="id" value={item.id} /><button className="admin-delete" aria-label={`Удалить вопрос ${item.question}`}><Trash2 aria-hidden="true" /></button></form></article>)}</div></section><section className="admin-panel"><span className="eyebrow">НОВЫЙ СЦЕНАРИЙ</span><h2>Добавить вопрос</h2><form action={createChatAnswerAction} className="admin-small-form"><label>Вопрос посетителя<input name="question" required placeholder="Например, что сейчас в наличии?" /></label><label>Короткий ответ<textarea name="answer" required rows={7} /></label><button className="button">Добавить ответ</button></form></section></div></>;
}
