import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { updateEquipmentAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/auth";

type Props = { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> };

export default async function EditEquipmentPage({ params, searchParams }: Props) {
  const [{ id }, { error }] = await Promise.all([params, searchParams]);
  const { supabase } = await requireAdmin();
  const { data: item } = await supabase.from("equipment").select("*").eq("id", id).maybeSingle();
  if (!item) notFound();
  return <><header className="admin-page-head compact"><div><Link href="/admin/catalog" className="admin-back"><ArrowLeft aria-hidden="true" />Каталог</Link><span className="eyebrow">РЕДАКТИРОВАНИЕ</span><h1>{item.name}</h1><p>Изменения появятся в каталоге после сохранения.</p></div></header>{error && <div className="admin-alert">Не удалось сохранить. Проверьте обязательные поля.</div>}
  <form action={updateEquipmentAction} className="admin-form"><input type="hidden" name="id" value={item.id} />
    <section><div className="admin-form-head"><span>01</span><div><h2>Карточка</h2><p>Название, категория и доступность.</p></div></div><div className="admin-fields three"><label>Название<input name="name" required defaultValue={item.name} /></label><label>URL-код<input name="slug" required defaultValue={item.slug} /></label><label>Бренд<input name="brand" required defaultValue={item.brand} /></label><label>Категория<select name="category" defaultValue={item.category}><option value="loaders">Погрузчики</option><option value="excavators">Экскаваторы</option><option value="dump-trucks">Самосвалы</option><option value="mixers">Миксеры</option><option value="attachments">Навесное</option></select></label><label>Статус<select name="status" defaultValue={item.status}><option value="in-stock">В наличии</option><option value="on-order">Под заказ</option></select></label><label>Новые фото<input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple /></label></div></section>
    <section><div className="admin-form-head"><span>02</span><div><h2>Параметры и цена</h2><p>Оставьте цену пустой для варианта «Уточнить».</p></div></div><div className="admin-fields three"><label>Ковш<input name="bucket" defaultValue={item.bucket ?? ""} /></label><label>Грузоподъёмность<input name="load_capacity" defaultValue={item.load_capacity ?? ""} /></label><label>Мощность<input name="power" defaultValue={item.power ?? ""} /></label><label>Двигатель<input name="engine" defaultValue={item.engine ?? ""} /></label><label>Гарантия<input name="warranty_hours" defaultValue={item.warranty_hours} /></label><label>Цена<input name="price" defaultValue={item.price ?? ""} /></label><label>Старая цена<input name="old_price" defaultValue={item.old_price ?? ""} /></label><label>Первый взнос<input name="down_payment" defaultValue={item.down_payment ?? ""} /></label><label>Платёж в месяц<input name="monthly_payment" defaultValue={item.monthly_payment ?? ""} /></label><label>Срок, месяцев<input name="installment_months" defaultValue={item.installment_months} /></label><label>Акция<input name="promo" defaultValue={item.promo ?? ""} /></label></div></section>
    <section><div className="admin-form-head"><span>03</span><div><h2>Текст и публикация</h2><p>Короткое и полное описание модели.</p></div></div><label>Короткое описание<textarea name="short_description" rows={3} required defaultValue={item.short_description} /></label><label>Полное описание<textarea name="description" rows={7} required defaultValue={item.description} /></label><label>Комплектация, по строке<textarea name="equipment" rows={5} defaultValue={(item.equipment as string[]).join("\n")} /></label><label>Ключевые слова<input name="keywords" defaultValue={(item.keywords as string[]).join(", ")} /></label><div className="admin-checks"><label><input type="checkbox" name="published" defaultChecked={item.published} />Опубликовано</label><label><input type="checkbox" name="featured" defaultChecked={item.featured} />На главной</label></div></section>
    <div className="admin-form-actions"><Link href="/admin/catalog" className="button button-outline">Отмена</Link><button className="button">Сохранить изменения</button></div>
  </form></>;
}
