"use client";

import { categoryLabels } from "@/lib/categories";
import { useRef, useState } from "react";
import { ImagePlus, X } from "lucide-react";
import { createEquipmentAction } from "@/app/admin/actions";

export function EquipmentForm() {
  const [files, setFiles] = useState<File[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);
  return <form action={createEquipmentAction} className="admin-form">
    <section><div className="admin-form-head"><span>01</span><div><h2>Основная информация</h2><p>Название и адрес карточки в каталоге.</p></div></div><div className="admin-fields two"><label>Название модели<input name="name" required placeholder="Например, LG968" /></label><label>URL-код<input name="slug" required pattern="[a-z0-9-]+" placeholder="lg968" /></label><label>Бренд<input name="brand" required defaultValue="LGZT" /></label><label>Категория<select name="category" defaultValue="loaders">{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></section>
    <section><div className="admin-form-head"><span>02</span><div><h2>Фотографии</h2><p>До 6 файлов JPG, PNG или WebP, каждый до 8 МБ.</p></div></div><button className="admin-upload" type="button" onClick={() => inputRef.current?.click()}><ImagePlus aria-hidden="true" /><strong>Выберите фотографии</strong><span>{files.length ? `${files.length} из 6 выбрано` : "Перетащите или нажмите для выбора"}</span></button><input ref={inputRef} className="sr-only" type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => setFiles(Array.from(event.target.files ?? []).slice(0, 6))} />{files.length > 0 && <div className="admin-file-list">{files.map((file) => <span key={`${file.name}-${file.size}`}>{file.name}<X aria-hidden="true" /></span>)}</div>}</section>
    <section><div className="admin-form-head"><span>03</span><div><h2>Характеристики</h2><p>Поля, по которым клиент сравнивает модели.</p></div></div><div className="admin-fields three"><label>Объём ковша<input name="bucket" placeholder="1,5 м³" /></label><label>Грузоподъёмность<input name="load_capacity" placeholder="2 т" /></label><label>Мощность, л.с.<input name="power" inputMode="numeric" /></label><label>Двигатель<input name="engine" placeholder="Weichai" /></label><label>Гарантия, моточасы<input name="warranty_hours" inputMode="numeric" defaultValue="3000" /></label><label>Доступность<select name="status" defaultValue="in-stock"><option value="in-stock">В наличии</option><option value="on-order">Под заказ</option></select></label></div><label>Комплектация, один пункт на строку<textarea name="equipment" rows={5} placeholder={'Кондиционер\nКамера заднего вида\nБыстросъём ковша'} /></label></section>
    <section><div className="admin-form-head"><span>04</span><div><h2>Цена и рассрочка</h2><p>Оставьте поле пустым, если цену нужно уточнять.</p></div></div><div className="admin-fields three"><label>Цена, сом<input name="price" inputMode="numeric" /></label><label>Старая цена<input name="old_price" inputMode="numeric" /></label><label>Первый взнос<input name="down_payment" inputMode="numeric" /></label><label>Платёж в месяц<input name="monthly_payment" inputMode="numeric" /></label><label>Срок, месяцев<input name="installment_months" inputMode="numeric" defaultValue="12" /></label><label>Промо-метка<input name="promo" placeholder="Выгода 80 000 сом" /></label></div></section>
    <section><div className="admin-form-head"><span>05</span><div><h2>Описание и публикация</h2><p>Пишите конкретно: задача, сильные стороны, условия.</p></div></div><label>Короткое описание<textarea name="short_description" rows={3} required /></label><label>Полное описание<textarea name="description" rows={7} required /></label><label>Ключевые слова через запятую<input name="keywords" placeholder="погрузчик, склад, 2 тонны" /></label><div className="admin-checks"><label><input type="checkbox" name="published" defaultChecked />Опубликовать сразу</label><label><input type="checkbox" name="featured" />Показывать в популярных</label></div></section>
    <div className="admin-form-actions"><a href="/admin/catalog" className="button button-outline">Отмена</a><button type="submit" className="button">Добавить технику</button></div>
  </form>;
}
