import Link from "next/link";
import { ArrowUpRight, CircleDollarSign, Eye, FileText, MessageSquareText, Package } from "lucide-react";
import { requireAdmin } from "@/lib/auth";

export default async function AdminDashboardPage() {
  const { supabase, profile } = await requireAdmin();
  const [{ count: products }, { count: leads }, { count: newLeads }, { count: views }] = await Promise.all([
    supabase.from("equipment").select("id", { count: "exact", head: true }),
    supabase.from("leads").select("id", { count: "exact", head: true }),
    supabase.from("leads").select("id", { count: "exact", head: true }).eq("status", "new"),
    supabase.from("analytics_events").select("id", { count: "exact", head: true }).in("event_name", ["page_view", "equipment_view"]),
  ]);
  return <><header className="admin-page-head"><div><span className="eyebrow">ПАНЕЛЬ УПРАВЛЕНИЯ</span><h1>Добрый день, {profile.full_name || "администратор"}</h1><p>Главное по каталогу и обращениям клиентов.</p></div><Link href="/admin/catalog/new" className="button">+ Добавить технику</Link></header><section className="admin-metrics"><article><span><Package aria-hidden="true" /></span><p>Моделей в базе</p><strong>{products ?? 0}</strong><small>Все записи каталога</small></article><article><span><MessageSquareText aria-hidden="true" /></span><p>Всего заявок</p><strong>{leads ?? 0}</strong><small>{newLeads ?? 0} ждут ответа</small></article><article><span><Eye aria-hidden="true" /></span><p>Просмотры</p><strong>{views ?? 0}</strong><small>С согласия посетителей</small></article><article><span><CircleDollarSign aria-hidden="true" /></span><p>Сделки</p><strong>—</strong><small>Отмечайте статус заявки</small></article></section><section className="admin-dashboard-grid"><article className="admin-panel"><div className="admin-panel-head"><div><span className="eyebrow">БЫСТРЫЙ СТАРТ</span><h2>Что можно сделать</h2></div></div><div className="admin-quick-links"><Link href="/admin/catalog/new"><Package aria-hidden="true" /><span><strong>Добавить модель</strong><small>Фото, параметры и рассрочка</small></span><ArrowUpRight aria-hidden="true" /></Link><Link href="/admin/leads"><MessageSquareText aria-hidden="true" /><span><strong>Разобрать заявки</strong><small>Новые обращения с сайта</small></span><ArrowUpRight aria-hidden="true" /></Link><Link href="/admin/content"><FileText aria-hidden="true" /><span><strong>Обновить контент</strong><small>Статьи и сервисные направления</small></span><ArrowUpRight aria-hidden="true" /></Link></div></article><article className="admin-panel admin-status-panel"><span className="eyebrow">СОСТОЯНИЕ СИСТЕМЫ</span><h2>Всё под контролем</h2><ul><li><i />Каталог подключён</li><li><i />Формы требуют явное согласие</li><li><i />First-party аналитика по согласию</li><li><i />Доступ защищён PostgreSQL RLS</li></ul></article></section></>;
}
