import Link from "next/link";
import { ArrowUpRight, FileText, Plus, Save, Wrench } from "lucide-react";
import { createPostAction, createServiceAction, deletePostAction, deleteServiceAction, updatePostAction, updateServiceAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/auth";
import { DestructiveSubmit } from "@/components/admin/destructive-submit";

type Props = { searchParams: Promise<{ created?: string; updated?: string; error?: string }> };

export default async function AdminContentPage({ searchParams }: Props) {
  const { created, updated, error } = await searchParams;
  const { supabase } = await requireAdmin();
  const [{ data: posts }, { data: services }] = await Promise.all([
    supabase.from("posts").select("id,title,slug,excerpt,published,published_at").order("created_at", { ascending: false }),
    supabase.from("services").select("id,title,slug,excerpt,published,sort_order").order("sort_order"),
  ]);
  return <><header className="admin-page-head"><div><span className="eyebrow">CMS</span><h1>Контент сайта</h1><p>Публикуйте статьи и сервисные направления без изменения кода.</p></div><Link href="/blog" className="button button-outline" target="_blank">Открыть блог <ArrowUpRight aria-hidden="true" /></Link></header>
    {(created || updated) && <div className="admin-success" role="status">Материал сохранён и уже доступен в системе.</div>}{error && <div className="admin-alert" role="alert">Проверьте обязательные поля и уникальность URL-кода.</div>}
    <section className="admin-cms-grid">
      <article className="admin-panel"><div className="admin-panel-head"><div><span className="eyebrow">НОВАЯ СТАТЬЯ</span><h2>Добавить в блог</h2></div><FileText aria-hidden="true" /></div><form action={createPostAction} className="admin-small-form"><div className="admin-fields two"><label>Заголовок<input name="title" minLength={3} maxLength={120} required /></label><label>URL-код<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="kak-vybrat-pogruzchik" required /></label><label>Рубрика<input name="category" defaultValue="Практика" required /></label><label>Время чтения<input name="read_time" defaultValue="5 минут" required /></label></div><label>Краткое описание<textarea name="excerpt" rows={3} minLength={10} maxLength={500} required /></label><label>Текст статьи<textarea name="content" rows={9} required placeholder={'Разделяйте абзацы пустой строкой.\n\nПишите только проверенные факты.'} /></label><label>Путь к изображению<input name="image" defaultValue="/images/products/heavy-site.jpg" required /></label><label className="admin-inline-check"><input type="checkbox" name="published" defaultChecked />Опубликовать сразу</label><button className="button" type="submit"><Plus aria-hidden="true" />Добавить статью</button></form></article>
      <article className="admin-panel"><div className="admin-panel-head"><div><span className="eyebrow">НОВАЯ УСЛУГА</span><h2>Добавить сервис</h2></div><Wrench aria-hidden="true" /></div><form action={createServiceAction} className="admin-small-form"><label>Название<input name="title" minLength={2} maxLength={120} required /></label><label>URL-код<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="diagnostika" required /></label><label>Короткое описание<textarea name="excerpt" minLength={10} maxLength={500} rows={5} required /></label><div className="admin-fields two"><label>Иконка<select name="icon" defaultValue="wrench"><option value="wrench">Инструмент</option><option value="package">Запчасти</option><option value="headphones">Консультация</option><option value="settings">Обслуживание</option></select></label><label>Порядок<input type="number" name="sort_order" defaultValue="10" /></label></div><label className="admin-inline-check"><input type="checkbox" name="published" defaultChecked />Показывать на странице сервиса</label><button className="button" type="submit"><Plus aria-hidden="true" />Добавить услугу</button></form></article>
    </section>
    <section className="admin-panel admin-content-list"><div className="admin-panel-head"><div><span className="eyebrow">УПРАВЛЕНИЕ</span><h2>Материалы</h2></div></div><div className="admin-content-columns"><div><h3>Статьи</h3>{posts?.map((post) => <details className="admin-content-item" key={post.id}><summary><span><strong>{post.title}</strong><small>/{post.slug} · {post.published ? "опубликована" : "черновик"}</small></span><span>Изменить</span></summary><form action={updatePostAction} className="admin-small-form admin-edit-form"><input type="hidden" name="id" value={post.id} /><label>Заголовок<input name="title" defaultValue={post.title} minLength={3} required /></label><label>Краткое описание<textarea name="excerpt" defaultValue={post.excerpt} minLength={10} rows={3} required /></label><label className="admin-inline-check"><input type="checkbox" name="published" defaultChecked={post.published} />Опубликована</label><button className="button" type="submit"><Save aria-hidden="true" />Сохранить</button></form><form action={deletePostAction} className="admin-delete-form"><input type="hidden" name="id" value={post.id} /><DestructiveSubmit label={`Удалить статью ${post.title}`} /></form></details>)}{!posts?.length && <p className="admin-muted">Статей пока нет.</p>}</div><div><h3>Сервисы</h3>{services?.map((service) => <details className="admin-content-item" key={service.id}><summary><span><strong>{service.title}</strong><small>/{service.slug} · {service.published ? "показывается" : "скрыт"}</small></span><span>Изменить</span></summary><form action={updateServiceAction} className="admin-small-form admin-edit-form"><input type="hidden" name="id" value={service.id} /><label>Название<input name="title" defaultValue={service.title} minLength={2} required /></label><label>Описание<textarea name="excerpt" defaultValue={service.excerpt} minLength={10} rows={3} required /></label><label>Порядок<input type="number" name="sort_order" defaultValue={service.sort_order} /></label><label className="admin-inline-check"><input type="checkbox" name="published" defaultChecked={service.published} />Показывать на сайте</label><button className="button" type="submit"><Save aria-hidden="true" />Сохранить</button></form><form action={deleteServiceAction} className="admin-delete-form"><input type="hidden" name="id" value={service.id} /><DestructiveSubmit label={`Удалить услугу ${service.title}`} /></form></details>)}{!services?.length && <p className="admin-muted">Добавленные услуги появятся здесь.</p>}</div></div></section></>;
}
